### ISSUE TITLE
Exception: fromstring() has been removed.

### ISSUE THREAD

**Issue by ways** [Fry-kun/pyseek#2]
Hi

I've installed this on ubuntu 16.04:
python2.7-pil.imagetk python-usb

I can hear the calibration click from the device, but get an exception:

sudo python2.7 seek.py
Traceback (most recent call last):
  File "seek.py", line 179, in <module>
    show_frame(first=True)
  File "seek.py", line 160, in show_frame
    disp_img = get_image()
  File "seek.py", line 122, in get_image
    calimg = Image.fromstring("I", (208,156), ret9, "raw", "I;16")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2063, in fromstring
    "Please call frombytes() instead.")
Exception: fromstring() has been removed. Please call frombytes() instead.

**Comment by chepebeto1010** [comment]
You have to replace all "fromstring" commands with "frombytes" and the issue should be solved

**Comment by ways** [comment]
Yep, worked.
